version: '3.8'

services:
  bolt-discord-bot:
    build: .
    environment:
      - BOLT_CLIENT_ID=${BOLT_CLIENT_ID}
      - BOLT_CLIENT_SECRET=${BOLT_CLIENT_SECRET}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_IDS=${DISCORD_GUILD_IDS}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add PostgreSQL for production
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=bolt_bot
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=your_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: